### ISSUE TITLE
Indexing Error During Predictions

### ISSUE THREAD

**Issue by nal10** [lhy0322/iEnhancer-BERT#1]
Trying to get predictions using the ReadME tutorial and getting the below error during run_prediction.py

```
09/23/2024 21:12:42 - INFO - __main__ -   ***** Running prediction  *****
09/23/2024 21:12:42 - INFO - __main__ -     Num examples = 86690
09/23/2024 21:12:42 - INFO - __main__ -     Batch size = 32
Predicting:   0%|          | 0/2710 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "run_enhancer.py", line 1287, in <module>
    main()
  File "run_enhancer.py", line 1157, in main
    prediction = predict(args, model, tokenizer, prefix=prefix)
  File "run_enhancer.py", line 518, in predict
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/iEnhancer-BERT/src/transformers/modeling_bert.py", line 1273, in forward
    all_layer = torch.transpose(torch.cat(tuple([t.unsqueeze(0) for t in outputs[2]]), 0), 0, 1)
IndexError: tuple index out of range
```

Based on what I can tell from DNABERT this is using the dev.tsv file. I have run the one from that repo using the 6kmer pretrained as well as one I created using the 3kmer and get the same error. below is the code I am running

```
import os

modelPath = "../data/DNABERT_models/3-new-12w-0"
dataPath = "../data/training_data/layer1_3mer"
outputPath = "../results"

os.system('python run_enhancer.py '
    '--model_type dna '
    '--tokenizer_name=' + modelPath + '/vocab.txt  '
    '--model_name_or_path ' + modelPath + ' '
   ' --task_name dnaprom '
   ' --do_predict '
  '  --data_dir ' + dataPath + '   '
   ' --max_seq_length 200 '
    '--per_gpu_pred_batch_size=32 '  
    '--output_dir ' + modelPath + '  '
   ' --predict_dir ' + outputPath + '  '
    '--n_process 4'
)
```

**Comment by lhy0322** [comment]
Hi, the pre-trained model provided by DNABERT is large-scale MLM unsupervised learning on a genome-wide scale. It doesn't have any knowledge of the downstream task, so you can't use DNABERT directly to predict enhancers (or strong/weak enhancers). You need to first train a model according to 3.1 3.2 (for your dataset or using the paper's dataset) and then make predictions.
